// Code generated by "stringer -type=Module"; DO NOT EDIT.

package golox

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModuleLexer-0]
	_ = x[ModuleParser-1]
	_ = x[ModuleResolver-2]
	_ = x[ModuleInterpreter-3]
}

const _Module_name = "ModuleLexerModuleParserModuleResolverModuleInterpreter"

var _Module_index = [...]uint8{0, 11, 23, 37, 54}

func (i Module) String() string {
	if i < 0 || i >= Module(len(_Module_index)-1) {
		return "Module(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Module_name[_Module_index[i]:_Module_index[i+1]]
}
