// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package lox

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenTypeUndefined-0]
	_ = x[TokenTypeLeftParen-1]
	_ = x[TokenTypeRightParen-2]
	_ = x[TokenTypeLeftBrace-3]
	_ = x[TokenTypeRightBrace-4]
	_ = x[TokenTypeComma-5]
	_ = x[TokenTypeDot-6]
	_ = x[TokenTypeSemicolon-7]
	_ = x[TokenTypePlus-8]
	_ = x[TokenTypeMinus-9]
	_ = x[TokenTypeStar-10]
	_ = x[TokenTypeSlash-11]
	_ = x[TokenTypeBang-12]
	_ = x[TokenTypeBangEqual-13]
	_ = x[TokenTypeEqual-14]
	_ = x[TokenTypeEqualEqual-15]
	_ = x[TokenTypeGreater-16]
	_ = x[TokenTypeGreaterEqual-17]
	_ = x[TokenTypeLess-18]
	_ = x[TokenTypeLessEqual-19]
	_ = x[TokenTypeString-20]
	_ = x[TokenTypeNumber-21]
	_ = x[TokenTypeVar-22]
	_ = x[TokenTypeNil-23]
	_ = x[TokenTypeTrue-24]
	_ = x[TokenTypeFalse-25]
	_ = x[TokenTypeAnd-26]
	_ = x[TokenTypeOr-27]
	_ = x[TokenTypeIf-28]
	_ = x[TokenTypeElse-29]
	_ = x[TokenTypeFor-30]
	_ = x[TokenTypeWhile-31]
	_ = x[TokenTypeFun-32]
	_ = x[TokenTypeReturn-33]
	_ = x[TokenTypeClass-34]
	_ = x[TokenTypeSuper-35]
	_ = x[TokenTypeThis-36]
	_ = x[TokenTypePrint-37]
	_ = x[TokenTypeIdentifier-38]
	_ = x[TokenTypeEOF-39]
}

const _TokenType_name = "TokenTypeUndefinedTokenTypeLeftParenTokenTypeRightParenTokenTypeLeftBraceTokenTypeRightBraceTokenTypeCommaTokenTypeDotTokenTypeSemicolonTokenTypePlusTokenTypeMinusTokenTypeStarTokenTypeSlashTokenTypeBangTokenTypeBangEqualTokenTypeEqualTokenTypeEqualEqualTokenTypeGreaterTokenTypeGreaterEqualTokenTypeLessTokenTypeLessEqualTokenTypeStringTokenTypeNumberTokenTypeVarTokenTypeNilTokenTypeTrueTokenTypeFalseTokenTypeAndTokenTypeOrTokenTypeIfTokenTypeElseTokenTypeForTokenTypeWhileTokenTypeFunTokenTypeReturnTokenTypeClassTokenTypeSuperTokenTypeThisTokenTypePrintTokenTypeIdentifierTokenTypeEOF"

var _TokenType_index = [...]uint16{0, 18, 36, 55, 73, 92, 106, 118, 136, 149, 163, 176, 190, 203, 221, 235, 254, 270, 291, 304, 322, 337, 352, 364, 376, 389, 403, 415, 426, 437, 450, 462, 476, 488, 503, 517, 531, 544, 558, 577, 589}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
